// Bindings are generated by `wails dev` into frontend/wailsjs/go/main/App.ts
// Until then, TypeScript will report missing module — this is expected.
import { StartTimer, PauseTimer } from '@wailsjs/go/main/App'

export const startTimer = (): Promise<string> => StartTimer()

export const pauseTimer = (): Promise<string> => PauseTimer()
